import type { UpsertOutcome } from '../../ai/rag/index'
import Elysia from 'elysia'
import { EMBEDDING_DIM, MODEL_ID } from '../../ai/rag/embedder'
import {
  clearRagIndex,
  getRagIndexStatus,
  queryRagIndex,
  upsertSnippetInRagIndex,
} from '../../ai/rag/index'
import { useStorage } from '../../storage'
import { aiDTO } from '../dto/ai'

const app = new Elysia({ prefix: '/ai' })

app
  .use(aiDTO)
  .post(
    '/mcp/ingest',
    async ({ body }) => {
      const storage = useStorage()
      const { id: snippetId } = storage.snippets.createSnippet({
        folderId: body.folderId ?? null,
        name: body.name,
      })

      for (const content of body.contents) {
        storage.snippets.createSnippetContent(snippetId, {
          label: content.label,
          language: content.language,
          value: content.value,
        })
      }

      if (body.description !== undefined) {
        storage.snippets.updateSnippet(snippetId, {
          description: body.description,
        })
      }

      const existingTags = storage.tags.getTags()
      const existingTagByName = new Map(
        existingTags.map(tag => [tag.name.toLowerCase(), tag.id]),
      )
      const createdTagIds: number[] = []

      for (const rawTagName of body.tags ?? []) {
        const tagName = rawTagName.trim()

        if (!tagName) {
          continue
        }

        const normalizedTag = tagName.toLowerCase()
        let tagId = existingTagByName.get(normalizedTag)

        if (!tagId) {
          tagId = storage.tags.createTag(tagName).id
          existingTagByName.set(normalizedTag, tagId)
          createdTagIds.push(tagId)
        }

        storage.snippets.addTagToSnippet(snippetId, tagId)
      }

      const snippet = storage.snippets.getSnippetById(snippetId)
      if (snippet) {
        await upsertSnippetInRagIndex(snippet)
      }

      return {
        createdTagIds,
        snippetId,
      }
    },
    {
      body: 'aiIngestMcpRequest',
      response: 'aiIngestMcpResponse',
      detail: {
        tags: ['AI'],
        summary: 'Ingest snippet generated by MCP workflow',
      },
    },
  )
  .post(
    '/rag/rebuild',
    async () => {
      const storage = useStorage()
      const snippets = storage.snippets.getSnippets({})

      const chunksBefore = getRagIndexStatus().chunks
      clearRagIndex()

      let chunksWritten = 0
      let skippedEmpty = 0
      let embedErrors = 0
      let storeErrors = 0
      let firstError: string | undefined

      const outcomes: UpsertOutcome[] = []
      for (const snippet of snippets) {
        outcomes.push(await upsertSnippetInRagIndex(snippet))
      }

      for (const o of outcomes) {
        chunksWritten += o.chunksWritten
        if (o.reason === 'empty')
          skippedEmpty += 1
        if (o.reason === 'embed-error') {
          embedErrors += 1
          if (!firstError && o.error)
            firstError = `embed: ${o.error}`
        }
        if (o.reason === 'store-error') {
          storeErrors += 1
          if (!firstError && o.error)
            firstError = `store: ${o.error}`
        }
      }

      return {
        chunksAfter: getRagIndexStatus().chunks,
        chunksBefore,
        chunksWritten,
        embedErrors,
        firstError,
        indexed: snippets.length,
        skippedEmpty,
        storeErrors,
      }
    },
    {
      response: 'aiRagRebuildResponse',
      detail: {
        tags: ['AI'],
        summary: 'Rebuild RAG index from snippets; reports per-stage counts',
      },
    },
  )
  .post(
    '/rag/query',
    async ({ body }) => {
      const items = await queryRagIndex(body.query, body.limit ?? 8)

      return {
        items,
      }
    },
    {
      body: 'aiRagQueryRequest',
      response: 'aiRagQueryResponse',
      detail: {
        tags: ['AI'],
        summary: 'Query snippets from in-memory RAG index',
      },
    },
  )
  .get(
    '/rag/status',
    () => {
      const { chunks, dbPath } = getRagIndexStatus()

      return {
        chunks,
        dbPath,
        embeddingDim: EMBEDDING_DIM,
        modelId: MODEL_ID,
      }
    },
    {
      response: 'aiRagStatusResponse',
      detail: {
        tags: ['AI'],
        summary: 'Inspect RAG index state (chunk count, db path, model)',
      },
    },
  )

export default app
