import Elysia from 'elysia'
import {
  clearRagIndex,
  queryRagIndex,
  upsertSnippetInRagIndex,
} from '../../ai/rag/index'
import { useStorage } from '../../storage'
import { aiDTO } from '../dto/ai'

const app = new Elysia({ prefix: '/ai' })

app
  .use(aiDTO)
  .post(
    '/mcp/ingest',
    async ({ body }) => {
      const storage = useStorage()
      const { id: snippetId } = storage.snippets.createSnippet({
        folderId: body.folderId ?? null,
        name: body.name,
      })

      for (const content of body.contents) {
        storage.snippets.createSnippetContent(snippetId, {
          label: content.label,
          language: content.language,
          value: content.value,
        })
      }

      if (body.description !== undefined) {
        storage.snippets.updateSnippet(snippetId, {
          description: body.description,
        })
      }

      const existingTags = storage.tags.getTags()
      const existingTagByName = new Map(
        existingTags.map(tag => [tag.name.toLowerCase(), tag.id]),
      )
      const createdTagIds: number[] = []

      for (const rawTagName of body.tags ?? []) {
        const tagName = rawTagName.trim()

        if (!tagName) {
          continue
        }

        const normalizedTag = tagName.toLowerCase()
        let tagId = existingTagByName.get(normalizedTag)

        if (!tagId) {
          tagId = storage.tags.createTag(tagName).id
          existingTagByName.set(normalizedTag, tagId)
          createdTagIds.push(tagId)
        }

        storage.snippets.addTagToSnippet(snippetId, tagId)
      }

      const snippet = storage.snippets.getSnippetById(snippetId)
      if (snippet) {
        await upsertSnippetInRagIndex(snippet)
      }

      return {
        createdTagIds,
        snippetId,
      }
    },
    {
      body: 'aiIngestMcpRequest',
      response: 'aiIngestMcpResponse',
      detail: {
        tags: ['AI'],
        summary: 'Ingest snippet generated by MCP workflow',
      },
    },
  )
  .post(
    '/rag/rebuild',
    async () => {
      const storage = useStorage()
      const snippets = storage.snippets.getSnippets({})

      clearRagIndex()

      for (const snippet of snippets) {
        await upsertSnippetInRagIndex(snippet)
      }

      return {
        indexed: snippets.length,
      }
    },
    {
      response: 'aiRagRebuildResponse',
      detail: {
        tags: ['AI'],
        summary: 'Rebuild in-memory RAG index from snippets',
      },
    },
  )
  .post(
    '/rag/query',
    async ({ body }) => {
      const items = await queryRagIndex(body.query, body.limit ?? 8)

      return {
        items,
      }
    },
    {
      body: 'aiRagQueryRequest',
      response: 'aiRagQueryResponse',
      detail: {
        tags: ['AI'],
        summary: 'Query snippets from in-memory RAG index',
      },
    },
  )
  .post(
    '/embedding/test',
    async ({ body, status }) => {
      try {
        const response = await fetch(body.endpoint, {
          method: 'POST',
          headers: {
            'Authorization': body.apiKey ? `Bearer ${body.apiKey}` : '',
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            input: ['connectivity-check'],
            model: body.model,
          }),
        })

        if (!response.ok) {
          return status(400, {
            ok: false,
            status: response.status,
          })
        }

        return {
          ok: true,
          status: response.status,
        }
      }
      catch (error) {
        console.error('Embedding endpoint test failed:', error)
        return status(500, {
          ok: false,
          status: 500,
        })
      }
    },
    {
      body: 'aiEmbeddingTestRequest',
      response: {
        200: 'aiEmbeddingTestResponse',
        400: 'aiEmbeddingTestResponse',
        500: 'aiEmbeddingTestResponse',
      },
      detail: {
        tags: ['AI'],
        summary: 'Test embedding endpoint connectivity',
      },
    },
  )

export default app
